### ISSUE TITLE
Error encountered when using

### ISSUE THREAD

**Issue by Karlkongcheng** [FFXIV-CombatReborn/RebornRotations#274]
Failed to invoke the next action, please contact support.
Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at RotationSolver.Basic.Helpers.ObjectHelper.IsTopPriorityHostile(IGameObject obj) in D:\a\RotationSolverReborn\RotationSolverReborn\RotationSolver.Basic\Helpers\ObjectHelper.cs:line 323
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at RotationSolver.Basic.Actions.ActionTargetInfo.<FindTargetByType>g__FindHostile|33_8(<>c__DisplayClass33_0&) in D:\a\RotationSolverReborn\RotationSolverReborn\RotationSolver.Basic\Actions\ActionTargetInfo.cs:line 970
   at RotationSolver.Basic.Actions.ActionTargetInfo.FindTargetByType(IEnumerable`1 IGameObjects, TargetType type, Single healRatio, SpecialActionType actionType) in D:\a\RotationSolverReborn\RotationSolverReborn\RotationSolver.Basic\Actions\ActionTargetInfo.cs:line 776
   at RotationSolver.Basic.Actions.ActionTargetInfo.FindTarget(Boolean skipAoeCheck, Boolean skipStatusProvideCheck) in D:\a\RotationSolverReborn\RotationSolverReborn\RotationSolver.Basic\Actions\ActionTargetInfo.cs:line 334
   at RotationSolver.Basic.Actions.BaseAction.CanUse(IAction& act, Boolean isLastAbility, Boolean isFirstAbility, Boolean skipStatusProvideCheck, Boolean skipComboCheck, Boolean skipCastingCheck, Boolean usedUp, Boolean skipAoeCheck, Boolean skipTTKCheck, Byte gcdCountForAbility) in D:\a\RotationSolverReborn\RotationSolverReborn\RotationSolver.Basic\Actions\BaseAction.cs:line 157
   at DefaultRotations.Tank.GNB_Default.DefenseAreaAbility(IAction nextGCD, IAction& act) in D:\a\RebornRotations\RebornRotations\BasicRotations\Tank\GNB_Default.cs:line 34
   at RotationSolver.Basic.Rotations.CustomRotation.UpdateDefenseActions(IAction& act) in D:\a\RotationSolverReborn\RotationSolverReborn\RotationSolver.Basic\Rotations\CustomRotation_Invoke.cs:line 109
   at RotationSolver.Basic.Rotations.CustomRotation.UpdateActions(JobRole role) in D:\a\RotationSolverReborn\RotationSolverReborn\RotationSolver.Basic\Rotations\CustomRotation_Invoke.cs:line 66
   at RotationSolver.Basic.Rotations.CustomRotation.TryInvoke(IAction& newAction, IAction& gcdAction) in D:\a\RotationSolverReborn\RotationSolverReborn\RotationSolver.Basic\Rotations\CustomRotation_Invoke.cs:line 21

**Comment by LTS-FFXIV** [comment]
what version of RSR and RebornRotations are you on?
